# -*- coding: utf-8 -*-
"""personal test for silver kampung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-vZitP8s-7GxIMeFebDmQidNk3u3Q6U
"""

#frontend movie selection, must add column border, change pill to link_button and add image.
import streamlit as st

st.title("Silver Kampong")
movies = [
        {"title": "My Children", "desc": "A man who values his children", "showtimes": "9.00 AM"},
        {"title": "Mein Kampf", "desc": "Is this source reliable?", "showtimes": "12.00 PM"},
        {"title": "Helloman", "desc": "Why am i doing this", "showtimes": "3.00 PM"}]

filters = st.menu_button("Filters", options=["All", "Showtimes"])
if filters == "All":
    col1, col2, col3 = st.columns(3, border =True, vertical_alignment="center")

    with col1:
        st.subheader(movies[0]["title"])
        st.caption(movies[0]["desc"])
        st.image("https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1138&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

        st.write("Showtimes:")
        st.button(movies[0]["showtimes"])


    with col2:
        st.subheader(movies[1]["title"])
        st.caption(movies[1]["desc"])
        st.image("https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1138&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

        st.write("Showtimes:")
        st.button(movies[1]["showtimes"])


    with col3:
        st.subheader(movies[2]["title"])
        st.caption(movies[2]["desc"])
        st.image("https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1138&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

        st.write("Showtimes:")
        st.button(movies[2]["showtimes"])
elif filters == "Showtimes":
    col1, col2, col3 = st.columns(3, border =True, vertical_alignment="center")
    showwtimes = [[movies[0]["showtimes"]. [movies][1]["showtimes"], [movies][2]["showtimes]]
    showtimes_filter = st.pills("", showtimes, selection_mode="multi")
    if showtimes_filter == movies[0]["showtimes"]:
        with col1:
            st.subheader(movies[0]["title"])
            st.caption(movies[0]["desc"])
            st.image("https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1138&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

            st.write("Showtimes:")
            st.button(movies[0]["showtimes"])
    if showtimes_filter == movies[1]["showtimes"]:
        with col2:
            st.subheader(movies[1]["title"])
            st.caption(movies[1]["desc"])
            st.image("https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1138&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

            st.write("Showtimes:")
            st.button(movies[1]["showtimes"])
    if showtimes_filter == movies[2]["showtimes"]: 
        with col3:
            st.subheader(movies[2]["title"])
            st.caption(movies[2]["desc"])
            st.image("https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1138&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

            st.write("Showtimes:")
            st.button(movies[2]["showtimes"])



